export const colors = [
    "red",
    "orange",
    "amber",
    "yellow",
    "lime",
    "green",
    "emerald",
    "teal",
    "cyan",
    "sky",
    "blue",
    "indigo",
    "violet",
    "purple",
    "fuchsia",
    "pink",
    "rose",
];

export const lightColors = [
    'bg-red-300',
    'bg-orange-300',
    'bg-amber-300',
    'bg-yellow-300',
    'bg-lime-300',
    'bg-green-300',
    'bg-emerald-300',
    'bg-teal-300',
    'bg-cyan-300',
    'bg-sky-300',
    'bg-blue-300',
    'bg-indigo-300',
    'bg-violet-300',
    'bg-purple-300',
    'bg-fuchsia-300',
    'bg-pink-300',
    'bg-rose-300',
];

export const jobCategories = [
    "Online Marketing",
    "Marketing",
    "Performance Marketing",
    "Content Marketing",
    "Social Media",
    "Project Management",
    "Sales",
    "E-Commerce",
    "CRM",
    "E-Mail Marketing",
    "SEO",
    "Online Editing & PR",
    "SEA",
    "Other",
    "Account Management",
    "Product Management",
    "Event- & Marketing Management",
    "Community Management",
    "Design & UX",
    "Data Marketing Analyst",
    "Infulencer Marketing",
    "Brand Management",
    "Display Marketing",
    "Tech & IT",
    "Amazon Marketing",
];

export const locations = [
    "Hamburg",
    "Berlin",
    "München",
    "Frankfurt am Main",
    "Köln",
    "Bremen",
    "Düsseldorf",
    "Stuttgart",
    "Braunschweig",
    "Sulzbach",
    "Wiesbaden",
    "Achern",
    "Bad Homburg",
    "Bonn",
    "Detmold",
    "Eschbach",
];

export const experiences = [
    "Professional",
    "Junior",
    "Senior",
    "Newcomer",
];

export const remotes = [
    "Hybrid",
    "On-Site",
    "100% Remote",
]